/**
 * Writes authored definitions into DatabaseSeeder.kt.
 *
 * The definitions live in scripts/meanings.json rather than being typed straight into the Kotlin,
 * so they can be reviewed as a single document, checked for length and duplication, and re-applied
 * after the corpus is regenerated by import_wordlist.js.
 *
 *   node scripts/apply_meanings.js [--dry-run]
 *
 * meanings.json maps "kasiguranin|english" (the sense key, lower-cased) to
 * { "en": "...", "tl": "..." }. A key that matches no entry is reported rather than ignored,
 * because a silent miss looks exactly like a word that was never written.
 */
const fs = require('fs');
const path = require('path');

const SEEDER = path.join(__dirname, '..', 'app', 'src', 'main', 'java', 'com', 'kasiguru', 'data', 'local', 'DatabaseSeeder.kt');
const MEANINGS = path.join(__dirname, 'meanings.json');
const MAX_LEN = 200;

const ENTITY = /VocabularyEntity\(([\s\S]*?)\n {8}\)/g;
const FIELD = /(\w+)\s*=\s*"([^"]*)"/g;

const norm = (s) => String(s || '').trim().toLowerCase();
const keyOf = (k, e) => norm(k) + '|' + norm(e);
const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');

function main() {
  const dry = process.argv.includes('--dry-run');
  if (!fs.existsSync(MEANINGS)) {
    console.error('No ' + MEANINGS + ' yet. Nothing to apply.');
    process.exit(2);
  }

  const meanings = JSON.parse(fs.readFileSync(MEANINGS, 'utf8'));
  let src = fs.readFileSync(SEEDER, 'utf8');
  const from = src.indexOf('fun getInitialVocabulary');
  const to = src.indexOf('fun getInitialStories');
  const head = src.slice(0, from);
  const tail = src.slice(to);
  let body = src.slice(from, to);

  const used = new Set();
  let written = 0;
  let alreadyHad = 0;
  const tooLong = [];

  body = body.replace(ENTITY, (block, inner) => {
    const f = {};
    for (const p of inner.matchAll(FIELD)) if (f[p[1]] === undefined) f[p[1]] = p[2];
    if (!f.kasiguranin) return block;

    const key = keyOf(f.kasiguranin, f.english);
    const m = meanings[key];
    if (!m) return block;
    used.add(key);

    const en = (m.en || '').trim();
    const tl = (m.tl || '').trim();
    if (en.length > MAX_LEN || tl.length > MAX_LEN) tooLong.push(key);
    if (!en && !tl) return block;
    if (f.meaningEnglish === en && f.meaningTagalog === tl) { alreadyHad++; return block; }

    // Drop any definition already present, then re-insert both immediately after category, which
    // is where the generator's field order puts them.
    let next = inner
      .replace(/,\n {12}meaningEnglish = "(?:[^"]*)"/, '')
      .replace(/,\n {12}meaningTagalog = "(?:[^"]*)"/, '');

    const add = [];
    if (en) add.push('            meaningEnglish = "' + esc(en) + '"');
    if (tl) add.push('            meaningTagalog = "' + esc(tl) + '"');
    if (!add.length) return 'VocabularyEntity(' + next + '\n        )';

    const insertion = ',\n' + add.join(',\n');
    if (/\n {12}category = "[^"]*"/.test(next)) {
      next = next.replace(/(\n {12}category = "[^"]*")/, '$1' + insertion);
    } else {
      next = next + insertion;
    }
    written++;
    return 'VocabularyEntity(' + next + '\n        )';
  });

  const unmatched = Object.keys(meanings).filter((k) => !used.has(k));

  console.log('Definitions in meanings.json: ' + Object.keys(meanings).length);
  console.log('Entries updated:              ' + written);
  console.log('Already up to date:           ' + alreadyHad);
  console.log('Keys matching no entry:       ' + unmatched.length);
  unmatched.slice(0, 40).forEach((k) => console.log('    ' + k));
  if (unmatched.length > 40) console.log('    ... and ' + (unmatched.length - 40) + ' more');
  if (tooLong.length) {
    console.log('Over ' + MAX_LEN + ' characters: ' + tooLong.length);
    tooLong.forEach((k) => console.log('    ' + k));
  }

  if (dry) { console.log('\nDry run, nothing written.'); return; }
  fs.writeFileSync(SEEDER, head + body + tail, 'utf8');
  console.log('\nWrote ' + SEEDER);
}

main();
